name: Deploy CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: "Deploy to Vercel"
        run: |
          npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.NEZLY_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.NEZLY_ORG_ID }}