name: Deploy CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: "Deploy to Vercel"
        run: |
          npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.NEZLY_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.NEZLY_ORG_ID }}