name: Deploy CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: "Deploy to Vercel"
        run: |
          npx vercel --token ${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.NEZLY_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.NEZLY_ORG_ID }}